development:
  adapter: postgresql
  encoding: utf8
  database: acting_website_development
  pool: 5
  username: rails
  password: password

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: acting_website_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: acting_website_production
  pool: 5
  username: 
  password: